name: update_pdf

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
      - constitution.tex

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Update tex
        run: |
          CURR_DATE=$( date +"%B %Y" )
          sed -i "s/\date{Last amended .*}/\date{Last amended $CURR_DATE}/g" constitution.tex
      - name: Compile tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: constitution.tex
      - name: Upload tex
        run: |
          git config --global user.name 'pdf-bot'
          git config --global user.email 'scs.phd.committee@gmail.com'
          git add -A
          git commit -m "update pdf"
          git push
